#!/usr/bin/env python3
"""Write catalog/RARITY.md from the mint manifest.

The shipped distribution otherwise exists only as a side effect of running
build_mint.py, whose report goes to output/ and is gitignored. This turns that
into a committed artifact.

It reads the GENERATED TOKEN METADATA in output/mint/metadata/, not the mint
manifest, so run build_mint.py first. That is deliberate: the table then
reports exactly the strings a collector sees, and cannot drift from them.

Deriving from the manifest instead needs a filename -> display-name mapping,
and that mapping is a bug farm. The first version of this tool did it and got
footwear wrong -- the manifest stores the OVERLAY filename
("layer-Shiba_Overlay_Right (1).png"), so the table said "Shiba Overlay Right"
where the metadata says "Shiba Slippers".

Re-run this after anything that moves the numbers: re-calibrating, renaming a
trait, retiring an asset, changing --n or the mint seed.

Usage (from repo root):
  python3 asset_assessment/build_mint.py --n 4444 --seed 4444
  python3 asset_assessment/build_rarity_table.py
"""

import argparse
import collections
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import generator as g            # noqa: E402
import build_mint as bm          # noqa: E402

METADATA_DIR = "output/mint/metadata"
OUT = "catalog/RARITY.md"
# canonical metadata order; presence-optional traits last
ALWAYS = ["Character", "Background", "Plate Tier", "Skin", "Eyes",
          "Mouth", "Trait Count"]
OPTIONAL = ["Footwear", "Arms", "Sticker", "Weather", "Artist"]


def _pct(count, n, dp=1):
    """A share at `dp` decimals, widened only if that would round it away to
    zero. The tiers span four orders of magnitude -- a 55 % skin down to a
    1-of-4444 secret rare -- and at the presence line's 1 decimal the rarest
    tier in the collection printed as "0.0%", which reads as none of them.

    Widening only the figures that need it is the point: a blanket reformat
    took Tornado from 0.32 % to 0.3 % and White skin from 55.47 % to 55.5 %,
    losing real precision everywhere to fix two lines."""
    p = 100.0 * count / n
    while dp < 4 and count and round(p, dp) == 0:
        dp += 1
    return f"{p:.{dp}f}%"


def _supply_note(n, toks):
    """One line on how the supply splits between composited characters and the
    standalone 1/1 secret rares. Written from the metadata rather than hard-
    coded, because it was hard-coded as "all composited" and went stale the
    moment the tier came back."""
    sr = sum(1 for t in toks if "Secret Rarez" in t)
    if not sr:
        return (f"**{n} tokens, all composited.** The 1/1 secret-rare tier is "
                "retired to `traits/secret_rarez_retired`, so every token is "
                "a character.\n")
    return (f"**{n} tokens: {n - sr} composited characters and {sr} "
            f"standalone 1/1 secret rares.** A secret rare is a finished "
            f"artwork minted as the whole token \u2014 no character, no plate, "
            f"no traits composited over it \u2014 so it carries a Secret "
            f"Rarez attribute instead of the usual breakdown, and every other "
            f"tier draws from the remaining {n - sr}.\n")


def load_tokens(d):
    toks = []
    for fn in os.listdir(d):
        if not fn.endswith(".json"):
            continue
        with open(os.path.join(d, fn)) as f:
            toks.append({a["trait_type"]: a["value"]
                         for a in json.load(f).get("attributes", [])})
    return toks


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--metadata", default=METADATA_DIR)
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--seed", type=int, default=4444,
                    help="the seed the metadata was built with (for the header)")
    args = ap.parse_args()

    toks = load_tokens(args.metadata)
    n = len(toks)
    if not n:
        sys.exit(f"no token metadata in {args.metadata} -- run build_mint.py first")

    # display name -> base name, so pinned-tier lookups still work
    disp2base = {v: k for k, v in g.TRAIT_NAMES[g.CHARACTERZ].items()}

    out = []

    def add(*xs):
        out.extend(xs)

    add("# Rarity table \u2014 Sweetardio Collection\n",
        f"Generated by `asset_assessment/build_rarity_table.py` from the token "
        f"metadata that `build_mint.py --n {n} --seed {args.seed}` writes \u2014 "
        f"{args.seed} is the seed the draw gains in "
        f"`traits/rarity_weights.json` are calibrated against. Regenerate "
        f"whenever the calibration is re-run or a trait is renamed.\n",
        _supply_note(n, toks),
        "Always-present traits (character, background, skin, eyes, mouth) are "
        "drawn by calibrated weight and land within ~0.2 points of target "
        "\u2014 roughly the sampling floor at this supply. Optional traits "
        "(arms, footwear, stickers, weather) and the legendary plates are "
        "slot-allocated to EXACT counts.\n",
        "Every value below is read straight from the shipped token metadata.\n")

    # ---- characters, with their tier ----
    counts = collections.Counter(t["Character"] for t in toks if "Character" in t)
    chase = min(bm.CHARACTER_COUNTS.values()) if bm.CHARACTER_COUNTS else None
    add("\n## Characters\n",
        f"{len(bm.CHARACTER_COUNTS)} of {len(counts)} pinned to exact counts; "
        "the rest are left unpinned so the legendary-background slots have "
        "characters to draw from.\n",
        "| character | count | share | tier |", "|---|---:|---:|---|")
    for k, v in sorted(counts.items(), key=lambda kv: kv[1]):
        base = disp2base.get(k, k)
        tier = ("chase" if bm.CHARACTER_COUNTS.get(base) == chase
                else "uncommon" if base in bm.CHARACTER_COUNTS else "common")
        add(f"| {k} | {v} | {100 * v / n:.2f}% | {tier} |")

    def table(title, key, note=""):
        c = collections.Counter(t[key] for t in toks if key in t)
        present = sum(c.values())
        add(f"\n## {title}\n")
        if note:
            add(note + "\n")
        if key in OPTIONAL:
            add(f"{present} of {n} carry this trait "
                f"({_pct(present, n)}); {n - present} do not.\n")
        add("| trait | count | share |", "|---|---:|---:|")
        for k, v in sorted(c.items(), key=lambda kv: kv[1]):
            add(f"| {k} | {v} | {_pct(v, n, dp=2)} |")

    table("Plate Tier", "Plate Tier",
          "**What a background is worth, stated on the token.** Plate rarity "
          "used to be legible only by counting the mint, and the count "
          "contradicted the label: at 50 each, every `Legendary` plate was "
          "more COMMON than 17 ordinary ones. Legendary is now 15 each, and "
          "the ladder is monotone \u2014 every Legendary is rarer than every "
          "ordinary plate. Derived from the designed target, so it is a "
          "property of the collection rather than of the seed that was minted.")
    table("Trait Count", "Trait Count",
          "**The axis collectors actually rank on**, and both tails are rarer "
          "than a Legendary plate. Five is the floor \u2014 character, "
          "background, skin, eyes and mouth are on every token \u2014 so a "
          "5 carries no arm, no footwear and no sticker. Counts Weather; does "
          "not count Plate Tier, which only restates the Background.")
    table("Backgrounds", "Background",
          "The four `Legendary` plates are slot-allocated at exactly 50 each "
          "and never appear in the weighted pick.")
    table("Eyes", "Eyes",
          "Calibrated, so the shares are chosen rather than left to the plate "
          "blocklist \u2014 which previously made Blue the rarest eye by "
          "accident.")
    table("Mouths", "Mouth")
    table("Skins", "Skin")
    table("Arms", "Arms", "Exact counts.")
    table("Footwear", "Footwear", "Exact counts.")
    table("Weather", "Weather",
          "**The animated tier.** A token with a Weather trait carries a "
          "seamless MP4 loop in `animation_url` as well as its still, and "
          "the still shows the weather too. Exact counts, and kept OFF the "
          "legendary plates \u2014 the point of a 1-of-50 background is that "
          "you can see it, and every weather state sits in front of it. So "
          "no token is both Legendary and animated.")

    table("Secret Rarez", "Secret Rarez",
          "**The 1/1 tier, and the rarest thing in the collection.** Each is a "
          "complete guest-artist artwork minted as the entire token, with "
          "nothing composited over it \u2014 so it has no character, plate, "
          "skin, eyes or mouth. One of each exists: **1 of "
          f"{n} = {100.0 / n:.4f}%**, ten times rarer than the Starfield "
          "plate (10 of " f"{n}" ") and fifty times rarer than a legendary "
          "background (50 of " f"{n}" ").")
    table("Artist", "Artist",
          "Guest artists, credited on the 1/1s they drew. The display name of "
          "the PIECE is its title; this is the person who made it, which for "
          "Duhnut Candy Man is a different string and appears nowhere else a "
          "collector can see \u2014 Emily Cartoons' signature is painted into "
          "the art and vanishes at thumbnail size. These tokens also carry the "
          "artist's own site in `external_url`. Minted with both artists' "
          "permission.")

    stk = sum(1 for t in toks if "Sticker" in t)
    distinct = len({t["Sticker"] for t in toks if "Sticker" in t})
    add("\n## Stickers\n",
        f"**{stk} of {n} carry a sticker ({100 * stk / n:.1f}%)** \u2014 "
        f"stickers are COMMON, so the {n - stk} bare tokens "
        f"({100 * (n - stk) / n:.1f}%) are the scarce case. A bare token has "
        "no Sticker attribute at all; \"no sticker\" is not a named trait.\n",
        f"The {distinct} sticker assets are spread evenly across those "
        "tokens.\n")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {args.out}  ({n} tokens)")


if __name__ == "__main__":
    main()
